---
title: 'RAF Technical Note: Processing Algorithms'
author: "RAF RSIG"
date: "9 Feb 2019"
site: bookdown::bookdown_site
documentclass: book
output: 
  bookdown::gitbook:
    lib_dir: assets
    split_by: "chapter+number"
  html_document: 
    css: columns.css
  pdf_document: 
    keep_tex: true
    includes:
      in_header: columns.tex
  #   config:
  #     toolbar:
  #       position: static
  # bookdown::pdf_book:
    # keep_tex: yes
  # bookdown::html_book:
    # css: toc.css
# documentclass: book
  # bookdown::gitbook:
    # includes:
      # in_header: preamble.tex
      #after_body: postbody.tex
    # lib_dir: "book_libs"
    # split_by: "chapter+number"
    #number_sections: true
    #toc: true
    #toc_float: true
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
```

# Preface {-#index}

Algorithms Used to Produce Data Products from Research Aircraft;  
also Definitions of Variables in Archived Data Files  

Previous PDF version of this document: [Old PDF Version](https://github.com/NCAR/aircraft_ProcessingAlgorithms/blob/master/ProcessingAlgorithms.pdf) <br />  
Download the current version in a browser for functional URL links. The .Rmd-format version can be accessed [here](https://htmlpreview.github.io/?https://github.com/WilliamCooper/ProcessingAlgorithms/blob/Rmd/index.html).  

```{r child='boxStyles.Rmd'}

```

```{r child='Section1.Rmd'}
```

```{r child='Section2.Rmd'}
```

```{r child='Section3.Rmd'}
```

```{r child='Section4.Rmd'}
```

```{r child='Section5.Rmd'}
```

```{r child='Section6.Rmd'}
```

```{r child='Section7.Rmd'}
```

```{r child='Section8.Rmd'}
```

```{r child='Section9.Rmd'}
```

```{r child='Section10.Rmd'}
```

```{r child='Appendices.Rmd'}
```


